### ISSUE TITLE
Spellchecker breaking

### ISSUE THREAD

**Issue by lkellar** [puffyboa/virtual-assistant#3]
I installed pyenchant but upon importing spellchecker I got this
````python
Traceback (most recent call last):
  File "/Users/Lak1681/PycharmProjects/virtual-assistant/jerf.py", line 16, in <module>
    from enchant.checker import SpellChecker
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/enchant/_enchant.py", line 121, in <module>
    prefix_dir.contents = c_char_p(e_dir)
TypeError: bytes or integer address expected instead of str instance
````

**Comment by jpsank** [comment]
Do you have the latest version of pyenchant? It looks like [this same error](https://github.com/rfk/pyenchant/issues/45) happens on version 1.6.6 or lower.

**Comment by lkellar** [comment]
It works now, thanks!
